settings:
  title: 'EARL Status & Performance'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 365 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: earl-apps # unique identifier
    name: Applications
    description: 'This refers to the web and mobile applications accessed by users.' # default=empty
    url: 'https://apps.earl.health/ED/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: earl-apis
    name: API's
    description: 'This refers to the system services and application programmable interfaces (APIs).'
    url: 'https://apps.earl.health/API/rest/Public/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true